### PR TITLE
added other benchmarks to the List benchmarks

### PR DESCRIPTION
**Pull request by druzn3k**
I restarted writing the benchmarks, adding the missing List functions. Feel free to contribute directly to this branch, that will remain open until most of the library will be covered.

### CODE REVIEW

**Comment by CyrusNuevoDia** [comment]
I think that they should be benchmarked against writing it in plain Elixir from the standard library, because otherwise they're not really showing anything. What do you think?

**Comment by druzn3k** [comment]
@knrz those are not benchmarks versus the standard library, those are benchmarks to catch performance regression between different versions of crutches. Benchfella is awesome, it saves the benchmarks results and has the ability to compare two running of the same bench, so it's best suited for this job. :)

**Comment by duijf** [comment]
I think @knrz meant something along the lines of the commit I just pushed.

**Comment by druzn3k** [comment]
uh ok. :+1: that wasn't my initial purpose, but we could do also that!

**Comment by duijf** [comment]
Feel free to revert my change if you feel it is out of place!

Just thought that pushing a commit would save you the trouble of including it from a comment of mine.

**Comment by druzn3k** [comment]
No, no problem in that, quite the contrary, thanks. My trouble with writing comparison benchmarks is that only a small subset of functions in crutches could be used that way, so if we are writing only those kind of benchmarks, it will be a short, short list. My initial purpose was giving contributors some metrics against which they could compare and, if they should modify an existing function, measure the impact of the modification on the overall performance.

**Comment by duijf** [comment]
Alright, then we're on the same page! LGTM.

**Comment by druzn3k** [comment]
LOL this was a WIP! I wanted to complete all the benchmarks before merging the branch.  :smile:

**Comment by duijf** [comment]
Oh, whoops :P Didn't read your first comment carefully enough. Sorry!

**Comment by druzn3k** [comment]
Ahah no problem. It's not the end of the world, I will open another branch/PR! :v:

**Pull request merged**
