### PR TITLE
List.split

### PR DESCRIPTION
**Pull request by philnash**
This is a first iteration. It passes all the tests I wrote for it, but I don't feel as though it is particularly Elixir-y. Got any tips to improve it?

Thanks!

### CODE REVIEW

**Comment by druzn3k** [comment]
Damn! I have implemented Array#split in #14, but haven't updated the title! I'm really sorry for the confusion. Let me know if I have to drop my implementation, and I will happily oblige (i really don't know enough of Elixir to understand which version is better or more idiomatic).

**Comment by philnash** [comment]
I like your implementation! Looks more idiomatic than mine at least, I like how you map the function over the original list to return tuples of the result and original value and pattern match on it. I think my formulation of the simple (non function) case to reformat as the function case introduces less repetition.

A collaboration of the two implementations would probably be best here. What do you think @druzn3k?

**Comment by druzn3k** [comment]
Seems a good idea to me. Let me update the code!

**Comment by mykewould** [comment]
@druzn3k @philnash Are we going with [PR 14](https://github.com/mykewould/crutches/pull/14)? Is there anything else that needs to be done here?

**Comment by mykewould** [comment]
I'll wait for you both to sign off before moving. Thank you for contributing! Love seeing the different approaches, and collaboration.

**Comment by druzn3k** [comment]
I updated the code in #14 with the @philnash's suggestion, so I'm good to go, but I will leave the final say to @philnash, because he invested time, and I am willing to drop my `List#split` if he want his implementation merged. :+1:

**Comment by philnash** [comment]
:+1: for merging #14. I'm really enjoying the collaboration and learning too!

**Comment by mykewould** [comment]
Awesome! Thank you both!

**Pull request closed without merging**
