### PR TITLE
New range functions and improvement on existing ones

### PR DESCRIPTION
**Pull request by eksperimental**
This PR adds new functions to Range.
- `Range.congruent?/2`
- `Range.contiguous?/2`
- `Range.sort/2`
- `Range.reverse/1`

Removed:
- `Range.normalize_order/1` (replaced by `Range.sort/2`)

Improvements: 
- `Range.overlaps?/2`: use `or` instead of `||`. and check only for three conditions, since the fourth one is not necessary
- `Range.union/2`: corrected to deal with ranges that are contiguous (Enum.union/2 behaves the same way)
- union/2 and intersection/2 optimized 
- Pattern matching improved in all functions. If not range is given the function won't match
- Docs improved
- IEx examples properly indented with 4 spaces.
- Tests written for each function in Range module.

### CODE REVIEW

**Comment by lpil** [comment]
I feel this PR would be much easier to review if each change was its own PR, rather than one large one.

**Comment by duijf** [comment]
@eksperimental Thanks a lot for the PR! I've added some comments to your proposed changes. Please check if you agree them :)

@lpil Normally I'd agree a changelog like this would be quite a chore, but in this case the commits are logical changes and separated quite nicely. So props!

**Comment by eksperimental** [comment]
@lpil I tried to squash as much as possible the commits (from 11 to 8),
but different PRs will make it impossible since following commits depend on the previous ones.
I know it's a lot but all these changes evolved as I as working on the idea.

**Comment by duijf** [comment]
Thanks for taking my suggestions into account! Tonight, I'll take a further look at it and hopefully can merge (life is getting in the way a bit)

**Pull request closed without merging**
