### PR TITLE
Attempt at to_sentence refactor.

### PR DESCRIPTION
**Pull request by mykewould**
@nawns My goal was to isolate the logical pieces and make the code a little bit more readable, but I'm curious as to what you think. Do you think this is a good path to go down? Anything to improve? General thoughts?

### CODE REVIEW

**Comment by druzn3k** [comment]
:+1: for `Crutches.List.shorten`

**Comment by mykewould** [comment]
It's great being able to drink our own champagne. Thanks to @duijf for the shorten method!

**Comment by mykewould** [comment]
@druzn3k any thoughts on performance or direction of the refactor? All feedback welcome.

**Comment by druzn3k** [comment]
I don't think that performances are a real issue here, @mykewould. Or, to be more precise, not at this stage. We are all learning here, and i think that optimizing "too much" could scare away possible contributors. Also, this library, as it's older sibling ActiveSupport, it's not built for high performance, but to simplifying common use cases not covered by the standard library, IMHO. For "happiness", stealing from the Ruby's lingo. Who would use `to_sentence` on a million words? Or even as "little" as a thousand? In conclusion, your refactoring as simple and as idiomatic as it could get without giving away readability, for me. :+1:

**Comment by mykewould** [comment]
I totally agree on all points @druzn3k. I love your explanation on performance. Looking ahead, I'd like to start capturing great explanations, like yours, in the Wiki. Right now I think that'd be a great piece for a FAQ on design, "should I optimize for performance?"... The goal would be to explain a lot of the ideas, methodologies, or design patterns that more experience contributors would just know. I'm still working through the details, as always, feedback, suggestions, and ideas are welcome.

What do you think?

**Comment by druzn3k** [comment]
I think that is a good idea, but the scope must be really clear and small, and focused on being a support for this project. Or otherwise this could became really fast a big fat mess. :shipit: 

I would love to help!

**Comment by duijf** [comment]
@mykewould Looks good. Maybe the methods to check options could be a feature of the library itself instead of private methods? I can see them being useful in other modules.

@druzn3k Glad you like the shorten method :)

**Comment by mykewould** [comment]
@duijf Great idea! I'll put it as a issue and circle back to it.

**Pull request merged**
