### PR TITLE
Improve the project's general documentation

### PR DESCRIPTION
**Pull request by duijf**
Hey everyone,

Did some work on the README and assorted files when I was offline. Here are the changes from my commit message:
- **Maybe needs discussion:** Worded the contributing pitch to also target others who are not coming from the Ruby world.
- Moved the licensing information to it's own file.
- Noted the Elixir and Erlang/OTP versions that we currently test against.
- Added a notice about the library being a moving target and not stable yet.
- Link to the wiki as well as the API reference.
- Moved the buttons down below the title.
- Added a thank you note in `CONTRIBUTING.md`
- 'Refactored' the links in `CONTRIBUTING.md`
- Clarify and consolidate the step by step guide on code contributions
- Changed the wording in the contributing bonus points section a bit
- Added a pointer to Inch CI in the contributing documentation section
- Add section on bug reports to `CONTRIBUTING.md`

Everything is up for debate of course. Especially the first point is something that could be up for debate.

Let me know what you think!

### CODE REVIEW

**Comment by druzn3k** [comment]
I don't know what @mykewould think about reaching developers other than the Rubists at this stage, if it's too early. I'm pro about opening the project to other kind of contributors, but this is still @mykewould project, and I think that he should have the last say.

This point aside, I think that the others addition are really great and an overall improvement on the previous documentation, thank you @duijf!

**Comment by jesuspc** [comment]
+1

**Comment by mykewould** [comment]
I'm not ready to leave the Ruby soliciting yet, but I'm ok with us addressing non-Rubyists. Thanks for putting this together!

**Comment by duijf** [comment]
@mykewould @druzn3k No problem :)

**Pull request merged**
