### PR TITLE
[28] The default mechanism for option resolution is used now at Helpe…

### PR DESCRIPTION
**Pull request by jesuspc**
…rs.Number#number_to_phone

### CODE REVIEW

**Comment by jesuspc** [comment]
A minor improvement over the previous PR for the issue suggested by @knrz

**Comment by druzn3k** [comment]
Thank you @jesuspc, but next time please give the PR a shorter title. :+1:

**Comment by jesuspc** [comment]
@druzn3k Will do! Sorry for that

**Comment by druzn3k** [comment]
No worries @jesuspc, we are still a work in progress, so there aren't strong rules. :) I added a first `CONTRIBUTING.md` if you want to take a look at it and give a feedback. :+1:

**Pull request merged**
