### PR TITLE
Add Map.filter and Map.reject

### PR DESCRIPTION
**Pull request by Erol**
Elixir core is [not planning on supporting Map.filter atleast for now](https://github.com/elixir-lang/elixir/pull/4554#issuecomment-214204197), so I am interested to know if this would be a good addition to Crutches. 😊

Examples:

```
iex> Map.filter(%{a: 1, b: nil}, fn ({_k, v}) -> not is_nil(v) end)
%{a: 1}

iex> Map.reject(%{a: 1, b: nil}, fn ({_k, v}) -> is_nil(v) end)
%{a: 1}
```

### CODE REVIEW

**Comment by druzn3k** [comment]
Unfortunately some tests are failing @Erol. Could you please fix those problems so I could review the code? Thanks! :+1: 

EDIT: I think I found the problem. `:maps` are part of the **Erlang 18.x** release, while Travis is testing against **Erlang 17.x**. Should we drop **17.x** compatibility? Any thought guys?

relevant logline: `Erlang/OTP Release 18.0 is not supported by Elixir 1.0.5. Using OTP Release 17.4.`

**Comment by Erol** [comment]
Yeah I've tested that against Erlang 18.x. If we need backwards compatibility, I can revert the code to use comprehensions instead.

**Comment by druzn3k** [comment]
Not sure if you should. In the Readme we state that is compatible with erlang 18, nothing about 17 compatibility. I'm also for dropping entirely elixir < 1.1 compatibility as we are approaching 1.3. :)

**Comment by Erol** [comment]
Great. I'll leave the code as is, and would just squash in the update to Travis if there's a consensus to drop Elixir 1.0.5. :)

**Comment by duijf** [comment]
Thanks for the PR @Erol!

Elixir 1.0.5 is [almost a year old](https://github.com/elixir-lang/elixir/releases/tag/v1.0.5), and there aren't a lot of breaking changes in the newer releases. So I think it is fair to drop support for 1.0.5 in our next release

**Comment by Erol** [comment]
Thanks for the merge!

**Pull request merged**
