### PR TITLE
Adds to_formatted_string

### PR DESCRIPTION
**Pull request by rickr**
First pass at #6.

Please feel free to rip this apart as I'm a complete elixir newb!

### CODE REVIEW

**Comment by CyrusNuevoDia** [comment]
@druzn3k @mykewould should this fall under the Crutches.Format umbrella? `Crutches.Format.List.as_formatted_string`?

**Comment by rickr** [comment]
Ah yes - I remember reading that. Good catch!

**Comment by druzn3k** [comment]
Uhm @rickr, this code is not working. `List.to_string` convert **integers representing codepoints** in a string. The string should be something like `[1,2,3]`, not `<<0, 1, 2, 3>>` (that's not even printable). Take a look at [Enum.join/2](http://elixir-lang.org/docs/stable/elixir/Enum.html#join/2) for how to join a collection of elements. :+1:

**Comment by druzn3k** [comment]
Any news @rickr?

**Comment by rickr** [comment]
@druzn3k Sorry for the delay - been a bit buried at work!

In trying to keep with the comments in #6 I wrote this so that any list passed to this function would obey standard elixir conventions (eg, be passed through to to_string). If it matched an ecto record the ids are extracted and THOSE are passed to to_string function. This would be in accordance with @duijf's comment about data being able to be easily transformed from one format to another.

I'm a bit too green to understand if this is useful or not but to me it does seem to take the spirit of the ActiveSupport method and place it into elixir. 

This may be a misunderstanding on my part and I'm more than happy to make any changes needed! Just let me know.

**Comment by druzn3k** [comment]
@rickr no need to be sorry, I was just checking. :)

Sorry, I forgot a `"` and added unnecessary `[]` in the comment before. I was trying to say that the result should be `"1, 2, 3"` and not '<<1, 2, 3>>', that is a binary data. The purpose of this function in ActiveSupport (IIRC, correct me if I'm wrong), is to have a representation that could be used in a SQL query.

**Comment by rickr** [comment]
Ah - I see what you're saying now! I can make that change but the reason it's like this now is due to me following the default behavior of to_string in elixir. I wasn't sure if we wanted to stray from that here. 

If that's the case I'll make the changes early next week!

**Comment by rickr** [comment]
@druzn3k  - hope you had a good weekend! I just pushed an update that converts the ids to strings and joins em up.

I also added a doctest that shows how a string works which I don't think was super intuitive.

**Comment by duijf** [comment]
@rickr Thanks for taking the time to look at this :)

Yup, strings are binaries and will only be represented in binary form&mdash;e.g. `<<97, 115, 100, 102>>` instead of "asdf"&mdash;when there's unprintable characters in it.

An easy way of forcing the binary form is to append a null byte, like so:

``` elixir
iex> "asdf" <> <<0>>
<<97, 115, 100, 102, 0>>
```

And I'm sorry to drag this on, but this case seems to fail for me (no test yet):

``` elixir
iex(1)> Crutches.List.to_formatted_string(["1","2","3"], :db)
"0, 1"
```

Probably because this is hard-coded in line 306:

``` elixir
_ -> List.foldr([%{id: 0}, %{id: 1}], [], fn x, acc -> [Integer.to_char_list(x.id) | acc] end) |> Enum.join(", ")
                ^^^^^^^^^^^^^^^^^^^^                                         ^^^^
```

Maybe create another clause that deals with lists of structs? Or maybe even better, another function that knows how to format a single type and call that on each element?

**Comment by rickr** [comment]
No problem at all for dragging this on. I admittedly don't have a good handle on the use case here. I'm totally open to any and all criticism!

This implementation would fail here because when passed :db it's expected to be given a collection of ecto records. In my limited elixir experience I've seen things saying 'dont be afraid to crash' so I didn't implement anything other than what would be expected. 

My questions: 
- Is that the wrong way of thinking?
- Isn't it on the user to provide a well formed struct when explicitly passing the :db argument?

**Comment by duijf** [comment]
Alright, the stuff below turned into a huge wall of text, sorry for that.

> No problem at all for dragging this on. I admittedly don't have a good handle on the use case here. I'm totally open to any and all criticism!

Glad to hear that :) It definitely is not all on you, Elixir and Ruby have different conventions and everyone gets confused every once in a while.

To make sure everyone reading this is on the same page, here is the relevant fragment of the ActiveSupport source code:

``` ruby
# Extends <tt>Array#to_s</tt> to convert a collection of elements into a
# comma separated id list if <tt>:db</tt> argument is given as the format.
#
#   Blog.all.to_formatted_s(:db) # => "1,2,3"
def to_formatted_s(format = :default)
  case format
  when :db
    if empty?
      'null'
    else
      collect(&:id).join(',')
    end
  else
    to_default_s
  end
end
alias_method :to_default_s, :to_s
alias_method :to_s, :to_formatted_s
```

In the above fragment it is indeed up to the user of the library to provide the `:db` argument if the array contains database records. It seems logical for us to do this as well.

> This implementation would fail here because when passed :db it's expected to be given a collection of ecto records. In my limited elixir experience I've seen things saying 'dont be afraid to crash' so I didn't implement anything other than what would be expected.

(Worded my reply ambiguously, sorry.) The implementation currently has a bug. It doesn't throw an error, but it gives a wrong answer when called with a normal list and given the `:db` argument. It would also give the wrong answer to any list of structs that isn't `%Foo{id: 0}, %Foo{id: 1}`.

> - Is that the wrong way of thinking?

I have a more nuanced opinion on this (others might disagree). As library authors, IMO we **either** need to let the programmer making use of our code decide when it crashes and when it doesn't, **or** pick between a throwing/non-throwing version. A function that throws an exception IMHO only needs a `!` at the end of it's name when you can pick between non-throwing and throwing.

Whenever we decide to throw an exception, though, it should be informative. When I remove the bug from your code like so:

``` elixir
def to_formatted_string(collection, format) when format === :db do
  case collection do
    [] -> "null"
    _ -> List.foldr(collection, [], fn x, acc -> [Integer.to_char_list(x.id) | acc] end) |> Enum.join(",")
  end
end
```

And call the function with wrong arguments, I get the following error:

``` elixir
iex(3)> Crutches.List.to_formatted_string(["1","2","3"], :db)
** (ArgumentError) argument error
               :erlang.apply("3", :id, [])
    (crutches) lib/crutches/list.ex:306: anonymous fn/2 in Crutches.List.to_formatted_string/2
      (elixir) lib/list.ex:117: List."-foldr/3-lists^foldr/2-0-"/3
    (crutches) lib/crutches/list.ex:306: Crutches.List.to_formatted_string/2
```

It looks like a library bug, but it is the fault of the user. The exception is okay, but could be better. The stack-trace is _not_ okay though, since it exposes function internals to the user.

> - Isn't it on the user to provide a well formed struct when explicitly passing the :db argument?

In this case, I do think it is on the user :)

Oh and I noticed three more things:
- `Crutches.List.to_formatted_string([1,2,3])` gives a binary with unprintable characters as a result (`<<1, 2, 3>>` instead of `"1,2,3"`).
- We might also want to throw an exception when called with an empty list.
- There is an inconsistency with the use of commas: `List.to_formatted_string([%User{id: 0}, %User{id: 1}], :db)` returns `"0, 1"` and `List.to_formatted_string(["1", "2", "3"])` returns `"123"`. I favour `"0,1"`/`"1,2,3"` over either of these.

Hope this is clear! Just ask here or shoot me an email if you can't figure something out.
Laurens

**Comment by rickr** [comment]
@duijf Thanks for the feedback great feedback! I'm going pull this PR back for now so someone else can take a shot. My time has become a bit limited lately.

We should probably update issue#6 with a clear way forward as well. There seems to be some ambiguity as far as expected results from this library vs what you would expect in elixir.

**Comment by druzn3k** [comment]
Issue #6 seems to be more confusing than helpful. I will close it and reopen a new issue that states more clearly what we should expect from `#to_formatted_string`. :+1:

**Pull request closed without merging**
