### PR TITLE
Add Crutches.List.init function

### PR DESCRIPTION
**Pull request by duijf**
This function returns every element in a list except the last one. It returns `nil` when said list is empty.

### CODE REVIEW

**Comment by mykewould** [comment]
@duijf what do you think of changing the name to .shorten? "init" is usually shorthand for "initialize", and this function seems to do more than just initialize a List. What are your thoughts?

**Comment by duijf** [comment]
I agree that the name isn't the best. More of a working name, since that is what the Haskell standard library uses. 

Shorten seems okay. I'll add the functionality to specify by how much tonight or tomorrow. One seems the best default to me.

**Comment by mykewould** [comment]
Cool! Additional functionality for how much sounds great.

**Comment by duijf** [comment]
@mykewould I've renamed the function and added the option to specify by how much :) Should be good, unless you have other remarks.

**Comment by mykewould** [comment]
@duijf Looks great!

**Pull request merged**
